#!/usr/bin/env python3
import sys
import os
if len(sys.argv) != 4:
  print("usage: " + sys.argv[0] + " (csv file) (s output) (h output)")
  exit(1)
count = 0
head, tail = os.path.split(sys.argv[1])
variableName = tail.removesuffix(".csv") + "Data"

data = []
with open(sys.argv[1], 'r') as fd:
  lines = fd.readlines()
  for line in lines:
    count += line.count(",") + 1
    data.append(line)

h_output = "#ifndef " + variableName + "_h\n" + \
  "  #define " + variableName + "_h\n" + \
  "  extern const short unsigned int " + variableName + "[" + str(count) + "];\n" + \
  "  #define " + variableName + "Length " + str(count * 2) + "\n" \
  "#endif"

output = "@ generated by mapToS.py\n" \
"@ data size = " + str(count * 2) + " bytes\n\n" \
".section .rodata\n" \
".align 2\n" \
".global " + variableName + "\n" \
".hidden " + variableName + "\n" + variableName + ":\n"
for line in data:
  output += ".hword " + line
output = output.rstrip(",\n") + "\n"

text_file = open(sys.argv[2], "w")
text_file.write(output)
text_file.close()

text_file = open(sys.argv[3], "w")
text_file.write(h_output)
text_file.close()